### ISSUE TITLE
Can't locate Role/TinyCommons/Collection/PickItems/Iterator.pm

### ISSUE THREAD

**Issue by eserte** [perlancar/perl-ArrayDataRoles-Standard#1]
t/with-PickItems-Iterator.t fails because of missing prereqs:
```
Can't locate Role/TinyCommons/Collection/PickItems/Iterator.pm in @INC (you may need to install the Role::TinyCommons::Collection::PickItems::Iterator module) (@INC contains: ...  .) at /usr/share/perl5/Role/Tiny.pm line 38.
t/with-PickItems-Iterator.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by perlancar** [comment]
fixed, thanks

**Comment by eserte** [comment]
@perlancar : the problem still exists with ArrayDataRoles-Standard-0.003

**Comment by perlancar** [comment]
The fix is now in 0.004.
